name: Build ARM Binary

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install ARM toolchain and Qt4
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
        sudo apt-get install -y qt4-dev-tools libqt4-dev cmake
    
    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake for old ARMv5
      working-directory: build
      run: |
        cmake .. \
          -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc \
          -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++ \
          -DCMAKE_CXX_FLAGS="-march=armv5te -msoft-float" \
          -DCMAKE_C_FLAGS="-march=armv5te -msoft-float" \
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      working-directory: build
      run: make
    
    - name: Strip binary
      working-directory: build
      run: arm-linux-gnueabi-strip JsonFetcher || true
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jsonfetcher-arm
        path: build/JsonFetcher
        retention-days: 30